# Homework 8b: Ising Model
Physics 177, Spring 2018  
**Due:** Tuesday, May 29

Trevor Ketcherside

## Discussion

This is the keystone project of our course. The Ising model for a magnet is characterized by the energy function:

$$E = - J\sum_{i,j}^\text{n.n.}s_i s_j$$

where 'n.n.' means "nearest neighbors" (the four adjacent cells in 2D).  Here $s_{i} = \pm 1$ is the **spin in the $z$-direction** of the electron at site `i`. We've chosen a convenient normalization. In fact, we'll choose convenient units where $J = \mu = k_B = 1$. 

## Problem 1: Ising Model

Simulate the 2D Ising model using Markov Chain Monte Carlo and the following parameters:

* `nSide = 20`, the number of nodes per side
* `nTemp = 100`, the number of temperature samples
* `Tmin = 1`, `Tmax = 4`, the mininum and maximum temperatures to scan
* `nStep = 10000`, the number of Monte Carlo steps to sample the microstates

**You should structure your program as follows:**  
* Define a variable `state` that is a `nSide` by `nSide` numpy array. Here's a good way to initialize it:

```python
state = 2*np.random.randint(2, size=(nSide,nSide))-1
```

* Define a function `mcmc(state, ii, jj, T)` that takes in a state, two indices (between `0` and `nSide-1`), and a temperature and outputs the state after one Markov Chain step.  
  
  
* The Markov Chain step should be as follows: look at the spin at position (`ii`, `jj`). Propose a step: flip the spin: `spin *= -1`. If that step is energetically favorable, do it. If not, roll the dice relative to $P = e^{-\Delta E/T}$. Note that `deltaE = 2*spin*Heff`, where the effective magnetic field is simply the sum of nearest neighbor spins.  
  
  
* What about boundary states? To simplify our lives, impose periodic boundary conditions. Thus the "neighbor to the right" of `state[ii,jj]` is `state[(ii+1)%nSide, jj]`.  
  
  
* Define a function `magnetization(state)` that takes in a state and outputs the sum of spins over all sites. The `np.sum` function may be useful.  
  
  
* Define a function `plotState(state)` that plots the spins. Here's a nice definition that you can use:
```python
def plotState(state):
    N = np.shape(state)[0]
    xs, ys = np.meshgrid(range(N), range(N))
    plt.axis('square')
    plt.axis((0,N-1,0,N-1))
    plt.pcolormesh(xs, ys, state, cmap=plt.get_cmap('binary'))
    plt.xticks([])
    plt.yticks([])
    plt.show
```
  
  
* To run the program: equilibrate the system at `Tmin`. This means running the Markov Chain step over and over again (*without* taking data) to make sure that the system settles to a low energy state. In other words, when you start sampling, you want to sample a "typical" microstate at `Tmin`, not an "unusually energetic" state. 
  
  
* Now scan over the `nTemp` temperature steps between `Tmin` and `Tmax`. For each temperature, run the Markov Chain to generate `nStep` microstate samples at that temperature. For each microstate, record the magnetization. Take the *average* magnetization at that temperature and record it in an array. (You'll want to also divide by `nStep**2` so that you get the average magnetization *per site*.) I called this array `mags`, you can call it something else.
  
  
* You can use the `timeit` package to time how long it takes to run the cell. With the default parameters above, it should take about a minute. You should, of course, be testing with much smaller numbers while you're writing your code. 
  
  
* Plot `mags` (the magnetization per site) as a function of temperature. You should observe a curve (perhaps a little sloppy looking) that looks like the one we sketched in <a href="https://github.com/Physics177-2018/Lecture_15">Lecture 15</a>. If your plot does not look like that, then play with the parameters. Did you equilibrate enough? (I found that I had to equilibrate for `3*nStep` = 30,000 steps to go from a random lattice to a lattice thermalized at `Tmin = 1`. 
  
  
* Use `plotState` to plot the system at `tMin` and `tMax`. Do these match what you expect? 

  
  
Here's what the magnetization should look like:
<img src="HW8b_sample2.png">

In [569]:
xs = []
def magn(input):
    return sum(map(sum, input))
    print(magn)
    xs.append(magn)

In [825]:
#I was not able to create the graph but i was able to get the magnetizations






import numpy as np
from math import sqrt, exp
from random import random, randrange
import random

nSide = 21
nTemp = 100
Tmin = 1
Tmax = 4
nStep = 10000


#i is colomb
#j is row








state = 2*np.random.randint(2, size=(nSide,nSide))-1
xs = []
def mcmc(state, i, j, T):
    N = np.shape(state)[0]
    print(state)
    xs.append(magn(state))
    heff = state[i+1][j] +state[i-1][j] + state[i][j+1] +state[i][j-1]
    deltaE = 2*state[i][j]*heff
    
    
    



    for i in range(nSide -1):
        for j in range(nSide -1):
            heff = state[i+1][j] +state[i-1][j] + state[i][j+1] +state[i][j-1]
            if (state[i][j]) == 1 and heff < 0:
                state[i][j] = -1
                
            if (state[i][j]) == -1 and heff > 0:
                state[i][j]=1
            else:
                x = random.uniform(-1,1)
                if x > 0:
                    x = 1
                elif x < 0:
                    x = -1
                state[i][j] = x 
                deltaE = 2*state[i][j]*heff
                p = exp(-deltaE/T)
               
                if random.uniform(0,100) < p:
                    state[i][j] *=-1
            
   
                
#I couldn't figure out what to do with the probability I was thought that i would use a random number between
# 0 and 100 if probabilty was less then 20% and random number was less then 20 then it would flip the state otherwise
#it would stay in the same state


In [868]:
mcmc(state,19,19,1)




#so i ran this multiple times to equilberate, i just hit shift enter a shitload of times 

[[ 1  1  1  1  1  1 -1  1  1  1  1  1  1  1 -1 -1 -1  1  1  1 -1]
 [ 1  1  1  1  1  1  1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [-1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [-1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1]
 [ 1  1  1

In [870]:
#sum of all the values in the array, total magnetization
def magn(input):
    return sum(map(sum, input))
    print(magn)

magn(state) # sum of equiliberated matrix


289

In [878]:

def magtemp(T):
    mcmc(state,19,19,T)

#function to run different temperatures through


In [881]:

maglist = [] # array of total magnetizations with different temperatures (couldn't get this part to work) i couldnt append the matrix's
temp = []  #array of temperatures from 1 to 4 with with 100 steps
nTemp = 100
Tmin = 1
Tmax = 4
xy = []

dStep = (Tmax-Tmin)/nTemp

Tmin =1
for i in range(nTemp):

    Tmin +=dStep
    temp.append(Tmin)
    maglist.append(magtemp(Tmin))
    
    
    



#matrixs at different temperatures starting from 1 to 4, using 100 steps




[[-1  1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1 -1  1 -1 -1 -1 -1 -1]
 [-1  1  1 -1  1  1 -1  1 -1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1  1  1  1  1  1  1]
 [-1  1  1  1  1 -1  1 -1  1 -1 -1  1  1  1 -1  1  1  1  1  1 -1]
 [-1 -1  1 -1 -1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1 -1 -1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1]
 [ 1  1  1 -1  1 -1  1 -1 -1 -1  1  1  1 -1 -1  1  1 -1 -1  1  1]
 [-1  1  1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1]
 [ 1  1  1 -1  1  1  1 -1  1  1 -1  1  1  1 -1  1  1 -1 -1  1 -1]
 [-1  1 -1 -1  1  1  1  1  1 -1  1  1 -1  1  1  1  1 -1  1  1  1]
 [ 1  1  1 -1  1 -1 -1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1 -1 -1 -1 -1 -1  1 -1  1  1  1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1 -1 -1 -1  1  1 -1 -1 -1]
 [-1  1  1 -1 -1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1]
 [ 1 -1 -1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1  1  1  1]
 [-1 -1  1

 [-1  1  1  1  1 -1  1 -1 -1  1  1  1 -1  1 -1  1 -1  1 -1  1  1]]
[[ 1 -1  1  1  1  1 -1  1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1 -1]
 [ 1 -1 -1  1  1  1 -1 -1 -1  1 -1 -1  1  1  1  1  1  1  1  1  1]
 [-1  1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1 -1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1 -1  1 -1 -1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1]
 [-1 -1  1  1 -1  1  1  1 -1  1  1  1 -1  1 -1  1 -1 -1 -1 -1  1]
 [ 1  1  1 -1 -1 -1  1  1  1  1  1  1 -1  1  1 -1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1  1  1  1 -1 -1 -1  1 -1  1  1 -1  1  1 -1 -1  1]
 [-1  1 -1 -1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1  1 -1 -1 -1  1  1  1 -1  1  1 -1  1  1 -1 -1 -1]
 [ 1  1 -1 -1  1  1  1 -1 -1  1  1  1  1 -1 -1 -1  1  1 -1  1  1]
 [ 1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1  1 -1  1  1  1]
 [ 1  1 -1  1 -1  1 -1  1  1  1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1]
 [ 1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1  1 -1 -1 -1  1 -1  1  1 -1]
 [-1 -1 -1  1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1  1 -1 -1  1 -1]
 [ 1 -1  

[61, 129, 75, 31, 33, 67, 83, 19, 69, 41, 69, 67, 59, 31, 29, 85, 93, 51, 17, 115, 53, 65, 57, 105, 45, 85, 55, 135, 91, 75, 113, 47, 49, 61, 55, 91, 83, 69, 37, 55, 59, 43, 55, 83, 71, 79, 45, 97, 31, 63, 47, 53, 41, 69, 59, 109, 71, 71, 63, 69, 113, 45, 91, 73, 49, 63, 59, 77, 65, 89, 95, 45, 51, 89, 95, 85, 85, 73, 49, 81, 71, 67, 53, 53, 13, 15, 65, 53, 87, 39, 25, 69, 77, 43, 97, 65, 57, 71, 73, 65]


In [415]:
def plotState(state):
  N = np.shape(state)[0]
  xs, ys = np.meshgrid(range(N), range(N))
  plt.axis('square')
  plt.axis((0,N-1,0,N-1))
  plt.pcolormesh(xs, ys, state, cmap=plt.get_cmap('binary'))
  plt.xticks([])
  plt.yticks([])
  plt.show

## Problem 2: animate!

Copy your solution to Problem 1 below. In this problem, we'll output an animated PNG of the lattice.  
  
  
Define a function `postState(state)` that is based on `plotState`, but instead saves the figure to a subfolder, `HW8b/` with some frame number. 

```python
    plt.savefig("HW8b/frame" + str(frame_num))
    plt.clf() # clear the plot after
```
  
Now modify the scan over temperatures so that at each temperature, (1) run `postState(state)`, (2) increment `frame_num`.  Then follow Homework 8a to use the `APNG` package to stitch together the individual frames into a single animated PNG. Include that image below. 
  
  
Here's an example of how it should look:
<img src="HW8b_sample.png">

(Note that this example has a small mistake, can you tell what it is?)

## Extra credit

Plot the **magnetic susceptibility**, 
$$\frac{1}{T}\left(\langle M^2 \rangle - \langle M \rangle^2\right)$$ 
as a function of temperature